Update uml
AY2223S2-CS2103T-T11-3/tp pull request #171
Opened 2023-03-27 16:11 UTC by bryansendeavour

2023-03-28 01:39 UTC, glozxi requested changes
Other than a nit, LGTM 😎

2023-03-28 01:39 UTC, glozxi commented on docs/images/NewContactActivityDiagram.png
Should the end node be changed to dot inside circle notation?

2023-03-28 15:15 UTC, bryansendeavour commented on docs/images/NewContactActivityDiagram.png
Great catch!

2023-03-28 15:44 UTC, glozxi commented on docs/images/NewContactActivityDiagram.png
Remember to change the png too!

2023-03-29 03:08 UTC, glozxi approved these changes
LGTM 😄

2023-03-29 03:08 UTC, merged