Add better clarify for the edit command
AY2223S2-CS2103T-T11-3/tp pull request #231
Opened 2023-04-04 05:58 UTC by engenhui1999

- Add better clarity to explain that editing of tags will remove all existing tags.
- Closes #222

2023-04-04 08:24 UTC, glozxi requested changes
LGTM with a nit

2023-04-04 08:24 UTC, glozxi commented on docs/UserGuide.md
> +- `RATE` must be a positive number and below 1,000,000.
Should `below 1,000,000` be in another sentence to be more consistent with the other commands in the UG?

2023-04-04 12:35 UTC, ExtraShotLatte reviewed
LGTM, just some nits about the where we place things! 👍

2023-04-05 10:26 UTC, glozxi approved these changes
LGTM 😃

2023-04-05 10:26 UTC, merged